# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f10ce1057aadaac489a61baede8968da60f6a3f7b4791e714b685a1f759dff2c9de1fefbaaf1047b27fe37eb8fbbc08eb071c5a9c2df04fed5b52ca295574c6

test:
  secret_key_base: 718703f1b7ff310a2d5c2c942f904cdf324988d0e47955fa243c59e0b9fb616eca1bab69372328a384ea0eaf9921b1c586251b31a9ba6d4d8fe9a55d2cd88f0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
